const SET_SORT_USERS_ACTION = `SET_SORT_USERS_ACTION`;
const SORT_USERS_ACTION = `SORT_USERS_ACTION`;
const CHANGE_USER_STATUS_ACTION = `CHANGE_USER_STATUS_ACTION`;

export { SET_SORT_USERS_ACTION, SORT_USERS_ACTION, CHANGE_USER_STATUS_ACTION };